# Fengwu Model Configuration - Light Version
# Lightweight version for fast training and low memory

# Temporal configuration
input_len: 7
output_len: 1
in_channels: 2  # u and v velocity components

# Spatial configuration
img_size: [240, 240]  # H, W

# Patch size
patch_size: [4, 4]         # 2D patch size (240/4 = 60 patches)
patch_size_3d: [2, 4, 4]   # 3D patch size

# Window size
window_size: [6, 12]       # 2D window (适配60x60 patches)
window_size_3d: [2, 6, 12] # 3D window

# Pseudo-3D depth
pseudo_3d_depth: 4

# Model architecture - LIGHT
embed_dim: 96              # Reduced from 192
num_heads: [3, 6, 6, 3]    # Reduced from [6, 12, 12, 6]
mlp_ratio: 4.0

# Regularization
drop_rate: 0.0
attn_drop_rate: 0.0
drop_path_rate: 0.1        # Reduced from 0.2

# Training hints
# - Fastest training speed
# - ~10-15M parameters
# - Suitable for quick experiments

