# Model name to config file mapping
OceanCNN: 'configs/models/cnn_conf.yaml'
OceanResNet: 'configs/models/resnet_conf.yaml'
OceanTransformer: 'configs/models/transformer_conf.yaml'

# Fuxi model variants (unified naming)
Fuxi: 'configs/models/fuxi_balanced_conf.yaml'  # Default: balanced version (recommended)
Fuxi_Light: 'configs/models/fuxi_light_conf.yaml'  # Lightweight: 13M params, fastest
Fuxi_Full: 'configs/models/fuxi_full_conf.yaml'  # Full: original architecture from reference_models
Fuxi_Auto: 'configs/models/fuxi_auto_conf.yaml'  # Autoregressive version

# NNG model variants (unified naming)
NNG: 'configs/models/nng_balanced_conf.yaml'  # Default: balanced version
NNG_Light: 'configs/models/nng_light_conf.yaml'  # Lightweight version (less memory)
NNG_Full: 'configs/models/nng_full_conf.yaml'  # Full: original architecture from reference_models
NNG_Auto: 'configs/models/nng_auto_conf.yaml'  # Autoregressive version

# OneForecast model variants (unified naming)
OneForecast: 'configs/models/oneforcast_balanced_conf.yaml'  # Default: balanced version (recommended)
OneForecast_Light: 'configs/models/oneforcast_light_conf.yaml'  # Lightweight: 5M params, GPU friendly
OneForecast_Full: 'configs/models/oneforcast_full_conf.yaml'  # Full: original architecture from reference_models
OneForecast_Auto: 'configs/models/oneforcast_auto_conf.yaml'  # Autoregressive version

# GraphCast model variants (adapted from weather prediction)
GraphCast: 'configs/models/graphcast_balanced_conf.yaml'  # Default: balanced version (recommended)
GraphCast_Light: 'configs/models/graphcast_light_conf.yaml'  # Lightweight: ~200K params, fast training
GraphCast_Full: 'configs/models/graphcast_full_conf.yaml'  # Full: ~5M params, best performance
GraphCast_Auto: 'configs/models/graphcast_auto_conf.yaml'  # Autoregressive: for long-term prediction

# Fengwu model variants (unified naming)
Fengwu: 'configs/models/fengwu_balanced_conf.yaml'  # Default: balanced version (recommended)
Fengwu_Light: 'configs/models/fengwu_light_conf.yaml'  # Lightweight: fast training
Fengwu_Full: 'configs/models/fengwu_full_conf.yaml'  # Full: original architecture from reference_models
Fengwu_Auto: 'configs/models/fengwu_auto_conf.yaml'  # Autoregressive: for long-term prediction

# Pangu model variants (unified naming) - Using Pangu2 (2D+3D hybrid) as standard
Pangu: 'configs/models/pangu_balanced_conf.yaml'  # Default: balanced version (recommended)
Pangu_Light: 'configs/models/pangu_light_conf.yaml'  # Lightweight: fast training
Pangu_Full: 'configs/models/pangu_full_conf.yaml'  # Full: based on references_models/pangu.py
Pangu_Auto: 'configs/models/pangu_auto_conf.yaml'  # Autoregressive: for long-term prediction

# Crossformer model variants (spatiotemporal Two-Stage Attention)
Crossformer: 'configs/models/crossformer_balanced_conf.yaml'  # Default: balanced version (recommended)
Crossformer_Light: 'configs/models/crossformer_light_conf.yaml'  # Lightweight: ~2-3M params, fast training
Crossformer_Balanced: 'configs/models/crossformer_balanced_conf.yaml'  # Balanced: ~10-15M params, good performance
Crossformer_Full: 'configs/models/crossformer_full_conf.yaml'  # Full: ~30-40M params, maximum capacity
Crossformer_Auto: 'configs/models/crossformer_auto_conf.yaml'  # Autoregressive: for long-term prediction
