# NNG Model Configuration - Lightweight version for testing
# Reduced complexity to lower memory usage

# Temporal configuration
input_len: 7        # Number of input frames
output_len: 1       # Number of output frames
in_channels: 2      # uo and vo components (ocean velocity)

# Spatial resolution
input_res: [240, 240]  # Spatial resolution (H, W)

# Graph mesh configuration - REDUCED
mesh_level: 4       # Reduced from 5 (coarser mesh)
multimesh: false    # Disable multi-resolution to save memory

# Model architecture parameters - REDUCED
hidden_dim: 64      # Reduced from 128
processor_layers: 8  # Reduced from 16 (fewer message passing layers)
aggregation: "mean"  # Use mean instead of sum (can be more stable)

# Optimization flags
use_cugraphops: false  # Disable CuGraphOps to avoid potential memory issues
add_3d_dim: false      # Disable pseudo-3D processing to save memory