# Transformer Model Configuration - 7 frames input, 1 frame output
input_len: 7
output_len: 1
in_channels: 2  # uo and vo components
patch_size: 8  # Standard ViT patch size (must divide image dimensions)
d_model: 256
nhead: 8
num_layers: 6
dim_feedforward: 1024
dropout: 0.1
